name: Main Workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: ollama --version

      # these tests to cover when the naming convention of the download files changed

      - name: asdf_plugin_test_0_3_6
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: ollama --version
          version: "0.3.6"

      - name: asdf_plugin_test_0_3_7
        uses: asdf-vm/actions/plugin-test@v2
        with:
          command: ollama --version
          version: "0.3.7"
